version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        UNAME: $USER
    # TODO change container_name
    container_name: python_app
    command: sleep infinity
