version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UNAME: $USER
    # TODO change container_name
    container_name: python_app_dev
    ports: 
      - 8888:8888
    volumes:
      - .:$HOME/app
    env_file:
      - .env
